name: Build and deploy Python app to Azure Web App - manishwebapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==65.5.0  # ✅ Downgrade setuptools
          pip install --no-build-isolation -r requirements.txt  # ✅ Critical fix

      - name: Collect static files (optional for Django)
        run: |
          python manage.py collectstatic --noinput || true

      - name: Zip project files for deployment
        run: |
          zip -r release.zip . -x "**/venv/*" "**/__pycache__/*" "**/.git/*"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B18360EDF6674DE3B819BEB12661C24A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5FB0B1E0A6B74014A6AF781216044A01 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B232911D402A41068942B949A528CD9C }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'manishwebapp'
          slot-name: 'Production'
